name: Build binaries
on: [push]

jobs:
    build:
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-24.04, ubuntu-24.04-arm]
        runs-on: ${{ matrix.os }}
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v6
            - uses: Swatinem/rust-cache@v2
            - name: Build
              run: cargo build --verbose --release
            - uses: actions/upload-artifact@v7
              with:
                  name: wol-relay-${{ matrix.os == 'ubuntu-24.04' && 'amd64' || 'arm64' }}
                  path: ./target/release/wol-relay

            - uses: docker/setup-buildx-action@v3
            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - uses: docker/build-push-action@v5
              with:
                  push: true
                  context: .
                  platforms: linux/amd64,linux/arm64
                  tags: ghcr.io/corebytee/wol-relay:latest-${{ matrix.os == 'ubuntu-24.04' && 'amd64' || 'arm64' }},ghcr.io/corebytee/wol-relay:${{ github.sha }}-${{ matrix.os == 'ubuntu-24.04' && 'amd64' || 'arm64' }}
